### PR TITLE
Utils tweak secret param handling

### PR DESCRIPTION
**Pull request by GeoDerp**

### CODE REVIEW

**Comment by davidusb-geek** [comment]
Hi. Are these necessary to avoid breaking the add-on?
I'm not very fond of all these try/except, I was thinking about other ways to come around this.

**Comment by GeoDerp** [comment]
These ones in particular, could get around easily by just setting a default value as the other option to get a statement (having only one get statement). 
It would just mean it won't try and take the value from the secrets file first. *(May be an issue if someone is running add-on mode not in HA. (which I'm guessing doesn't happen anyway))*
The other try statements on the lists would need to be looked into deeper for another way around if the list exists and what to replace with if else. 
Maybe a simple fix. When I get some free time I'll have a look.

**Comment by davidusb-geek** [comment]
Is this related to theses changes?
https://community.home-assistant.io/t/emhass-an-energy-management-for-home-assistant/338126/1779?u=davidusb

**Comment by davidusb-geek** [comment]
> Is this related to theses changes? https://community.home-assistant.io/t/emhass-an-energy-management-for-home-assistant/338126/1779?u=davidusb

Well this is more a missing key on that default dict

**Comment by GeoDerp** [comment]
Both solar.forcast and solcast should be broken. That was the main reason for both pull requests initially. Would have to check if that's related to that comment however.

**Comment by GeoDerp** [comment]
Closed due to #169 being merged. 
Could reopen if someone is wrong with #169.

**Comment by davidusb-geek** [comment]
I did had to revert back to this solution after today's crash...

**Comment by GeoDerp** [comment]
@davidusb-geek sorry to hear, what went wrong, anything I can fix?

**Comment by davidusb-geek** [comment]
This issue https://github.com/davidusb-geek/emhass-add-on/issues/74#issue-2117220193

**Comment by davidusb-geek** [comment]
So I went back with the option on this PR, tested the add-on properly and published a patch release.
I'm just about to release a new patched version to finally solve #154 that wasn't solved before because an error of mine.

**Comment by GeoDerp** [comment]
> This issue https://github.com/davidusb-geek/emhass-add-on/issues/74#issue-2117220193

Would you like me to see if I can work out the issue?

**Comment by davidusb-geek** [comment]
Well like we discussed I did found that code more proper.
Unfourtunately it failed but in the rush I didn't debugged that code completely and just switched to this PR.
It could be interesting to improve to that other more proper version. But we will need to test the add-on properly before release. I did tested the docer standalone before release but it wasn't sufficient.
So finally are you able to properly test the add-on using these dev containers?
I added this option to test an add-on-like option.json but while using the docker standalone mode which is much more easy and fast to compile and test: https://github.com/davidusb-geek/emhass/blob/0f5335ffb102ce57b34e90cded4e7a817f96bce3/src/emhass/web_server.py#L140

**Comment by GeoDerp** [comment]
Personally I have been using this method to get semi close: 
https://github.com/davidusb-geek/emhass/pull/147#issuecomment-1925578995

But also there is a docker file in the pull request that also tries to emulate the add-on environment. Not as easily to use however.

**Comment by GeoDerp** [comment]
Looks like the issue is with def_start_timestep/def_end_timestep. It's almost like it's being overridden somehow. I'm wondering if reverting it fixed the issue ?

**Comment by GeoDerp** [comment]
Edit: I have worked out the problem and its possibly sooooo dumb

**Pull request closed without merging**
