### PR TITLE
generate test image from master

### PR DESCRIPTION
**Pull request by GeoDerp**
In theory, this additional github action will run every time a commit has been pushed into the master branch.
It will automatically generate a `test` tagged image, which could be used to test the latest changes on emhass-add-on / docker, prior to pushing a new release. 

*It also makes it easier for other users to check the changes and add comments before releasing.*

### CODE REVIEW

**Comment by davidusb-geek** [comment]
And how can we launch this image?
Something like this?
```
docker run -it -p 5000:5000 --name emhass-test -v ./options.json:/data/options.json emhass/test
```
With some secrets defined in `options.json` to access the HA instance

**Comment by GeoDerp** [comment]
Should be the exact same as the original. however you will be pulling from `ghcr.io/davidusb-geek/emhass:test` instead of `ghcr.io/davidusb-geek/emhass:v0.11.4`
you can also select the `emhass-test` version from emhass-add-on

just hold for two secs before merging however, I think I found a tag bug.

**Comment by GeoDerp** [comment]
looks good now 

This is what it looks like on emhass-add-on

**Comment by davidusb-geek** [comment]
> looks good now 👍
> 
> p.s. This is what it looks like on emhass-add-on Screenshot From 2024-12-29 23-55-53

Great, thanks for this!

**Review by davidusb-geek — APPROVED** [review]

**Pull request merged**
