### PR TITLE
Github Actions - Google OSV scan

### PR DESCRIPTION
**Pull request by GeoDerp**
Check for known vulnerabilities in Python and Debian packages inside EMHASS container.

### CODE REVIEW

**Comment by GeoDerp** [comment]
There are quite a bit of possible vulnerabilities. I'm thinking of exploring a dedicated package manager to help assist in version control 🤔.
Maybe like Poetry, PDM or Litestar. What do you think @davidusb-geek ?

**Comment by davidusb-geek** [comment]
> There are quite a bit of possible vulnerabilities. I'm thinking of exploring a dedicated package manager to help assist in version control 🤔. Maybe like Poetry, PDM or Litestar. What do you think @davidusb-geek ?

Do you think that adding a dedicated package manager will help on vulnerability issues? I'm not very fond of those, I always stick with plain and simple venv and pip. But if they can help solve vulnerability issues then why not

**Comment by davidusb-geek** [comment]
One thing we need to do is migrate to a full pyproject.toml and drop thz setup.py config

**Comment by davidusb-geek** [comment]
@GeoDerp, This PR is ready to merge?

**Comment by GeoDerp** [comment]
> @GeoDerp, This PR is ready to merge?

Not yet, Ill include the pyproject.toml convertion on this PR also.

**Comment by GeoDerp** [comment]
currently looking into the issue:
```
#10 68.06 ERROR: Cannot install skforecast because these package versions have conflicting dependencies.
#10 68.06 
#10 68.06 The conflict is caused by:
#10 68.06     numba 0.60.0 depends on llvmlite<0.44 and >=0.43.0dev0
#10 68.06     numba 0.59.1 depends on llvmlite<0.43 and >=0.42.0dev0
#10 68.06     numba 0.59.0 depends on llvmlite<0.43 and >=0.42.0dev0
```

**Comment by davidusb-geek** [comment]
You surely saw it when merging the master, I did added the conversion file pyproject.toml and I tested it. It works fine including the special dependencies option to do for example : `pip install emhass[test]`

**Comment by GeoDerp** [comment]
the numba issue looks to be a arm issue based on the skforecast==0.14.0 upgrade. 
I think Ill have it fixed soon.

**Comment by GeoDerp** [comment]
Still working on it. Defiantly  `armv7` and `armhf` issue so piwheels package with skforecast.

**Comment by GeoDerp** [comment]
I think I found the issue.

**Comment by GeoDerp** [comment]
So on piwheels, `skforecast` is present and so is `numba`. However there is no `llvmlite`
```
├── skforecast [required: ==0.14.0, installed: 0.14.0]
│   ├── joblib [required: >=1.1, installed: 1.4.2]
│   ├── numba [required: >=0.59, installed: 0.60.0]
│   │   ├── llvmlite [required: >=0.43.0dev0,<0.44, installed: 0.43.0]
│   │   └── numpy [required: >=1.22,<2.1, installed: 1.26.4]
```
Trying some methods of working around the issue.

**Comment by GeoDerp** [comment]
Looks like the llvmlite temp fix works. Now its just the package vulnerabilities again

**Comment by GeoDerp** [comment]
@davidusb-geek , this PR should be good to go 👍

I have suppressed the docket build and publish actions from failing when a vulnerability is found just because there are packages that are debian version pacific.

**Review by davidusb-geek — APPROVED** [review]

**Pull request merged**
