### PR TITLE
web_server addon mode init data_path options param

### PR DESCRIPTION
**Pull request by GeoDerp**

### CODE REVIEW

**Comment by GeoDerp** [comment]
Created from suggestion by @gieljnssns :
https://github.com/davidusb-geek/emhass/pull/147#issuecomment-1986783742

**Comment by GeoDerp** [comment]
Will let you know when I am happy with this.

**Comment by GeoDerp** [comment]
@davidusb-geek , there is an issue with the directory structure of the webserver on EMHASS-Add-on *(since it uses its own ul)*. Will try and fix this and add it to this PR.

**Comment by GeoDerp** [comment]
Not my finest work. But I think it works.

**Review by davidusb-geek — APPROVED** [review]

**Comment by davidusb-geek** [comment]
Ok I will merge now and test later today.

**Pull request merged**
