### PR TITLE
patch fix cec path issue

### PR DESCRIPTION
**Pull request by GeoDerp**
@davidusb-geek

### CODE REVIEW

**Comment by GeoDerp** [comment]
This should work. This is because the root path is `/data` for forecast.py

**Comment by GeoDerp** [comment]
This is not ideal. As its placed in the data directory. I may still change to use parent paths to fix this.

**Comment by davidusb-geek** [comment]
Ok I see. Many thanks!

**Comment by GeoDerp** [comment]
#247 Tries to fix these types of issues.

**Review by davidusb-geek — APPROVED** [review]

**Pull request merged**
