### PR TITLE
Upgrade to python 3.11

### PR DESCRIPTION
**Pull request by pail23**
- Upgrade to python version 3.11
- Upgrade numpy, scipy, pandas and tables to match python 3.11

### CODE REVIEW

**Review by davidusb-geek — CHANGES_REQUESTED** [review]
This files also needs to be changed: docs/requirements.txt
But most importantly no checks were run. 
At least this workflow will need an update: .github/workflows/python-test.yml

**Comment by davidusb-geek** [comment]
Tests are failing, probably related to those changes on TZ and datetimes?

**Comment by pail23** [comment]
Many thanks for your reviews. The tests should be fixed now and docs/requirements.txt is updated.

**Review by davidusb-geek — APPROVED** [review]

**Comment by davidusb-geek** [comment]
There are a lot of errors with Python 3.11. The Numpy version is not backwards compatible with Python 3.9 for example. How can we solve this? @pail23

**Comment by davidusb-geek** [comment]
Python are getting these errors: https://community.home-assistant.io/t/emhass-an-energy-management-for-home-assistant/338126/1566

**Comment by pail23** [comment]
As a quick thought: Would it be possible to migrate the emhass addon to python 3.11?

According this the [release notes](https://numpy.org/news/) of numpy 1.26, this version should be compatible with python 3.9-3.12.

I will have a look at the error messages an see if there are other options.

**Comment by davidusb-geek** [comment]
> As a quick thought: Would it be possible to migrate the emhass addon to python 3.11?

Ok, but how to do this?

**Comment by davidusb-geek** [comment]
The problem seems to be with the pvlib package using the h5py package...

**Comment by pail23** [comment]
I did not test, but we might be able to update to python 3.11 by replaceing `bullseye` with `bookworm` in `
emhass-add-on/emhass/build.yaml
`

```

build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  armhf: ghcr.io/home-assistant/armhf-base-debian:bookworm
  armv7: ghcr.io/home-assistant/armv7-base-debian:bookworm
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
```

**Comment by davidusb-geek** [comment]
Ok I will try that. Thanks!

**Comment by pail23** [comment]
As an alternative:

According to this [article](https://stackoverflow.com/questions/74852225/attributeerror-module-numpy-has-no-attribute-typedict), it might help to explcitly install a newer h5py version (h5py==3.10.0)

**Comment by davidusb-geek** [comment]
I added h5py==3.10.0 as a hard requirement but that does not seems to be the only problem.
There seems to be an issue with pip3 an PEP 668.
For now a solution was found using the flag --break-system-packages on pip3 install commands.
Let's see if it works.

**Comment by davidusb-geek** [comment]
Build are failing for the armhf architectures.
It is a shame to leave those out, there is no full support for Python3.11 yet on that architecture I guess.
https://github.com/davidusb-geek/emhass-add-on/actions/runs/7241702872

**Pull request merged**
