### PR TITLE
Docker Standalone Publish Workspace Fix

### PR DESCRIPTION
**Pull request by GeoDerp**
https://github.com/davidusb-geek/emhass/issues/205

### CODE REVIEW

**Comment by GeoDerp** [comment]
@davidusb-geek , Im trying to test the DockerHub integration, however having some issues. I may need you to test this one your end.

**Comment by davidusb-geek** [comment]
Ok. I just manually launched the docker publish workflow and it is still failing with some authentication issue.

**Comment by GeoDerp** [comment]
Considering how long arm v7 takes to build, I may finish testing this tomorrow.  (I think I Just have to check the tags work appropriately now).

So `public_docker.yaml` has been modified using: https://docs.docker.com/build/ci/github-actions/multi-platform/ as an example.

This workflow benefits as it distributes all the architectures to different runners (making it faster and similar to Emhass-Add-on's matrix).

`docker-build-test.yaml` file has also been created as an subset of this that works to test the build of each architecture (just like the implementation on EMHASS-Add-on )

**Comment by GeoDerp** [comment]
@davidusb-geek , this has been tested. Should be good to go.

**Review by davidusb-geek — APPROVED** [review]

**Pull request merged**
