### PR TITLE
possible data path and addon arg fix

### PR DESCRIPTION
**Pull request by GeoDerp**

### CODE REVIEW

**Comment by GeoDerp** [comment]
Currently testing. May try and simulate the addon container directory structure of the add-on container as best as possible.

**Comment by davidusb-geek** [comment]
The working folder for the docker standalone mode (no add-on) is `/app`.
In this PR you erased the pointers to `/app`. This will probably break the docker standalone mode.
Yesterday I tested this mode and works perfectly.
The problem is with the add-on mode.

**Comment by GeoDerp** [comment]
I wonder if the run.sh should be like:

```bash
#!/usr/bin/with-contenv bashio
# ==============================================================================
# Start EMHASS service
# ==============================================================================

export CONFIG_PATH="/usr/src/config_emhass.yaml"
export OPTIONS_PATH="/data/options.json"
export DATA_PATH="/data/" 

exec python3 -m emhass.web_server --url "http://supervisor/core/api" --key "$SUPERVISOR_TOKEN" --addon "True"
```
?

**Comment by GeoDerp** [comment]
docker file I created to test the addon as close as I can make it without emulating HA
```dockerfile
#Test Addon via Docker Emulation
#Docker run example: 
## docker build . -t emhass-addon -f AddonEmulateDocker && docker run  -e CONFIG_PATH="/usr/src/config_emhass.yaml" -e "SECRETS_PATH=/usr/src/secrets_emhass.yaml"  -e DATA_PATH="/data/" -e OPTIONS_PATH="/data/options.json" emhass-addon --url $URL --key $KEY
FROM --platform=$BUILDPLATFORM debian:stable AS build
WORKDIR /usr/src

# copy the requirements file into the image
COPY ./requirements.txt /usr/src/requirements.txt

# Setup
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libffi-dev \
        python3.11 \
        python3 \
        python3-pip \
        python3-dev \
        git \
        build-essential \
        gcc \
        coinor-cbc \
        coinor-libcbc-dev \
        libglpk-dev \
        glpk-utils \
        libhdf5-dev \
        libhdf5-serial-dev \
        netcdf-bin \
        libnetcdf-dev \
        pkg-config \
        gfortran \
        libatlas-base-dev \
    && ln -s /usr/include/hdf5/serial /usr/include/hdf5/include \
    && export HDF5_DIR=/usr/include/hdf5 \
    && pip3 install --extra-index-url=https://www.piwheels.org/simple --no-cache-dir --break-system-packages -U setuptools wheel \
    && pip3 install --extra-index-url=https://www.piwheels.org/simple --no-cache-dir --break-system-packages -r requirements.txt \
    && apt-get purge -y --auto-remove \
        python3-pip \
        python3-dev \
        git \
        build-essential \
        libhdf5-dev \
        libhdf5-serial-dev \
        pkg-config \
        gfortran \
    && rm -rf /var/lib/apt/lists/*

#install local emhass 
#RUN git clone https://github.com/davidusb-geek/emhass.git
#pip install emhass (original)
COPY ./. /tmp/emhass
WORKDIR /tmp/emhass
RUN python3 setup.py install


WORKDIR /

# copy contentsusr/src
COPY config_emhass.yaml /usr/src
COPY options.json /data/

#unused in production, used temporarily for testing
COPY secrets_emhass.yaml /usr/src/ 

# Labels
LABEL \
  io.hass.name="emhass" \
  io.hass.description="EMHASS: Energy Management for Home Assistant" \
  io.hass.version=${BUILD_VERSION} \
  io.hass.type="addon" \
  io.hass.arch="aarch64|amd64|armhf|armv7"

ENTRYPOINT [ "python3", "-m", "emhass.web_server", "--addon", "True" ]
```

**Comment by GeoDerp** [comment]
When testing I couldn't find any issue besides the setting directories. Let me know if you get more errors and ill test again [👍](https://emojipedia.org/thumbs-up)

**Comment by davidusb-geek** [comment]
Ok thanks. I will merge, test it as it is and if that fails then I will look into the `run.sh` suggestion.

**Review by davidusb-geek — APPROVED** [review]

**Comment by GeoDerp** [comment]
aaaaaaaaaah. I see why its the /app (although learning how /app gets generated) now. However I still think options isnt in there so:
```
I wonder if the run.sh should be like:

```bash
#!/usr/bin/with-contenv bashio
# ==============================================================================
# Start EMHASS service
# ==============================================================================

export OPTIONS_PATH="/data/options.json"
exec python3 -m emhass.web_server --url "http://supervisor/core/api" --key "$SUPERVISOR_TOKEN" --addon "True"
```

**Comment by GeoDerp** [comment]
If the run.sh modification is required you may only need to parse in the options environment variable.

**Pull request merged**
