### PR TITLE
Advanced and Basic Pages

### PR DESCRIPTION
**Pull request by GeoDerp**
- Tool icon has been added to switch between basic and advanced mode.
- Advance, basic, script have been made into there own files and referenced in index.html .

### Basic
Screenshot from 2024-03-01 21-38-08

### Advanced
Screenshot from 2024-03-01 21-38-15

### CODE REVIEW

**Comment by GeoDerp** [comment]
@davidusb-geek , feel free to just pull in this PR and I will close RP #211.

**Comment by davidusb-geek** [comment]
> @davidusb-geek , Feel free to just pull in this PR and I will close RP #211.

Ok let's go with this then.
However could we just let that button on the basic page to just run the optimization without publishing anything. People will just run the optimization and then inspect the graphs. This is useful for testing and setting the add-on parameters without publishing undesired results to HA sensors.

**Comment by GeoDerp** [comment]
> > @davidusb-geek , Feel free to just pull in this PR and I will close RP #211.
> 
> Ok let's go with this PR then. However could we just let that button on the basic page to just run the optimization without publishing anything. People will just run the optimization and then inspect the graphs. This is useful for testing and setting the add-on parameters without publishing undesired results to HA sensors.

Sounds good. Give me a couple of minutes,

**Comment by GeoDerp** [comment]
@davidusb-geek , there you go. Sorry also tweaked the spacing quickly.

**Review by davidusb-geek — APPROVED** [review]

**Pull request merged**
